In [1]:
import numpy as np
import math as mat

Inisialisasi data masukkan dan target yang diinginkan serta bobot dan bias awal serta learning rate

In [2]:
inputData = np.array([[1, 0, 0, 0, 1, 0],
                      [0, 1, 1, 1, 1, 0],
                      [0, 0, 1, 0, 0, 1],
                      [0, 0, 1, 0, 1, 0],
                      [0, 1, 0, 0, 0, 1],
                      [1, 0, 1, 0, 1, 1],
                      [0, 0, 1, 1, 0, 0],
                      [0, 1, 0, 1, 0, 0],
                      [1, 0, 0, 1, 0, 1],
                      [0, 1, 1, 1, 1, 1]])
target = np.array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [3]:
w_in=np.array([
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1]
])
w_hid=np.array([0.1, 0.1, 0.1])
bias_hid=np.array([0.1, 0.1, 0.1])
bias_out=np.array([0.1])
input_hidden=np.zeros(3)

learning_rate=0.1

Pemecahan data menjadi data train dan data test

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputData, target, test_size=0.25, random_state=0)
print(x_train, y_train)
print(x_test, y_test)

[[0 1 1 1 1 1]
 [0 1 1 1 1 0]
 [0 0 1 1 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [1 0 1 0 1 1]] [1 1 1 1 0 0 0]
[[0 0 1 0 0 1]
 [1 0 0 1 0 1]
 [0 1 0 0 0 1]] [0 1 0]


In [5]:
def sigma_count(x_in, w_in, b_in):
    sigma_sum=0
    for i in range(len(x_in)):
        sigma_sum+=x_in[i]*w_in[i]
    sigma_sum+=b_in
    return sigma_sum

In [6]:
def sigmoid_count(x_input):
    x_input=x_input*(-1)
    sigmoid_value=1/(1+mat.exp(x_input))
    return sigmoid_value

In [7]:
def forward_count(x_in, w_in_layer, w_hid_layer, b_hid_layer, b_out_layer):
    for x in range(len(input_hidden)):
        w_in_col=w_in_layer[:, x]
        input_hidden[x]=sigma_count(x_in, w_in_col, b_hid_layer[x])
    for x in range(len(input_hidden)):
        input_hidden[x]=sigmoid_count(input_hidden[x])
    
    outlayer_in=sigma_count(input_hidden, w_hid_layer, b_hid_layer[0])
    forward_output=sigmoid_count(outlayer_in)
    return forward_output

In [15]:
def backprop(err, x_in, forward_output):
    global w_in
    global w_hid
    global bias_hid
    global bias_out
    d_out=forward_output*(1-forward_output*err)
    d_in_hidden=np.zeros(len(input_hidden))
    for x in range(len(input_hidden)):
        d_in_hidden[x]=learning_rate*d_out*input_hidden[x]
    d_bias_in_hidden=learning_rate*d_out
    d_hidden_layer=np.zeros(len(w_hid)) #len(w_hid)
    for x in range(len(d_hidden_layer)):
        d_hidden_layer[x]=input_hidden[x]*(1-input_hidden[x])*d_out*w_hid[x]
    d_in=np.zeros(w_in.shape)
#     print(len(d_in))
    for x in range(len(d_in)):
        for y in range(len(d_in[0])):
            d_in[x][y]=learning_rate*d_hidden_layer[y]*x_in[x]
    d_bias_in=learning_rate*d_hidden_layer
#     adjust_weight(d_in, d_in_hidden, d_bias_in_hidden, d_bias_in)
    w_in=w_in+d_in
    w_hid=w_hid+d_in_hidden
    bias_hid=bias_hid+d_bias_in_hidden
    bias_out=bias_out+d_bias_in

In [16]:
def train_data(epoch):
    for a in range(epoch):
        for i in range(len(x_train)):
            input_x=x_train[i, :]
            output_y=y_train[i]
            forward_output=forward_count(input_x, w_in, w_hid, bias_hid, bias_out)
            err=output_y-forward_output
            backprop(err, input_x, forward_output)

In [19]:
train_data(20)
print(w_in)
print(w_hid)
print(bias_hid)
print(bias_out)

[[0.23940133 0.23940133 0.23940133]
 [0.20035388 0.20035388 0.20035388]
 [0.33439022 0.33439022 0.33439022]
 [0.24141552 0.24141552 0.24141552]
 [0.37374385 0.37374385 0.37374385]
 [0.18582963 0.18582963 0.18582963]]
[38.96230477 38.96230477 38.96230477]
[39.45102168 39.45102168 39.45102168]
[0.4581937 0.4581937 0.4581937]


In [24]:
result=np.zeros(len(x_test))
for x in range(len(result)):
    result[x]=forward_count(x_test[x], w_in, w_hid, bias_hid, bias_out)

In [31]:
print(result)
print(y_test)
result_=result-y_test
sum_acc=0
for x in (result_):
    if x==0:
        sum_acc+=1
acc=sum_acc/len(result_)

[1. 1. 1.]
[0 1 0]


In [32]:
print("The accuracy is: ")
print(acc)

The accuracy is: 
0.3333333333333333
